name: Test Package

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart format --fix --set-exit-if-changed .
      - run: dart analyze
